### ISSUE TITLE
Contact page email

### ISSUE THREAD

**Issue by kknundy** [Soumyabrata/Soumyabrata.github.io#1]
Email address can be hotlinked in html using href="mailto:email@server.com". Other options exist to preset bcc, subject, etc. 
Examples: http://www.tutorialspark.com/html5/HTML5_email_mailto.php
Another option could be a web based contact form.

**Comment by Soumyabrata** [comment]
Great! Thanks for the wonderful feedback!

Let me try sorting it out.
